version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - jwt-db
    environment:
      - HIC_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jwt-db:5432/authentication

  server:
    build: ./server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - gateway

  jwt-db:
    image: postgres:13.7-alpine
    container_name: jwt-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=authentication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres